### ISSUE TITLE
CloudEvent 'data' attributes are passed to function inputs as strings

### ISSUE THREAD

**Issue by tenczar** [vmware/dispatch#451]
## Bug Report
While trying to subscribe to events with a python or java function if the event includes a data payload both functions fail on deserializing their input. This can be seen best with these two executions:

```
{
    "blocking": true,
    "executedTime": 1526513318,
    "faasId": "a5666367-ade7-4b79-aa39-569770fe5fdd",
    "finishedTime": 1526513318,
    "functionId": "a7a43694-9916-4b59-ab41-231f24db9b5b",
    "functionName": "java-fn",
    "input": {
        "name": "Jon",
        "place": "Winterfell"
    },
    "logs": {
        "stderr": null,
        "stdout": null
    },
    "name": "2a5ae81a-5588-44e6-b9f1-ec0cbae7f9cf",
    "output": "Hello, Jon from Winterfell",
    "reason": null,
    "secrets": [],
    "services": null,
    "status": "READY",
    "
```

and

```
{
    "event": {
        "cloud-events-version": "0.1",
        "content-type": "application/json",
        "event-id": "6f3fee2b-8ffb-49cb-b1ea-aa6601c1fada",
        "event-time": "2018-05-16T16:26:46.400-07:00",
        "event-type": "symphony2",
        "namespace": "dispatchframework.io",
        "source-id": "dispatch",
        "source-type": "dispatch"
    },
    "executedTime": -62167134794,
    "faasId": "a5666367-ade7-4b79-aa39-569770fe5fdd",
    "finishedTime": 1526513206,
    "functionId": "a7a43694-9916-4b59-ab41-231f24db9b5b",
    "functionName": "java-fn",
    "input": "{\"name\" : \"Jon\", \"place\" : \"Winterfell\"}",
    "logs": {
        "stderr": [
            "com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $",
            "\tat com.google.gson.Gson.fromJson(Gson.java:900)",
            "\tat com.google.gson.Gson.fromJson(Gson.java:953)",
            "\tat io.dispatchframework.javabaseimage.SimpleFunctionExecutor.applyFunction(SimpleFunctionExecutor.java:90)",
            "\tat io.dispatchframework.javabaseimage.SimpleFunctionExecutor.execute(SimpleFunctionExecutor.java:61)",
            "\tat io.dispatchframework.javabaseimage.POJFunctionServer$ExecFunction.lambda$handleRequest$0(POJFunctionServer.java:73)",
            "\tat io.undertow.io.AsyncReceiverImpl.receiveFullString(AsyncReceiverImpl.java:140)",
            "\tat io.undertow.io.AsyncReceiverImpl.receiveFullString(AsyncReceiverImpl.java:79)",
            "\tat io.dispatchframework.javabaseimage.POJFunctionServer$ExecFunction.handleRequest(POJFunctionServer.java:72)",
            "\tat io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)",
            "\tat io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)",
            "\tat io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)",
            "\tat io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)",
            "\tat io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:151)",
            "\tat io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)",
            "\tat io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:51)",
            "\tat org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)",
            "\tat org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)",
            "\tat org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)",
            "\tat org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)",
            "\tat org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)",
            "\tat org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)",
            "\tat org.xnio.nio.WorkerThread.run(WorkerThread.java:466)",
            "Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at path $",
            "\tat com.google.gson.internal.bind.JsonTreeReader.expect(JsonTreeReader.java:162)",
            "\tat com.google.gson.internal.bind.JsonTreeReader.beginObject(JsonTreeReader.java:87)",
            "\tat com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)",
            "\tat com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)",
            "\tat com.google.gson.Gson.fromJson(Gson.java:888)",
            "\t... 21 more"
        ],
        "stdout": null
    },
    "name": "401729bb-7d10-406f-9b1a-09156aef5148",
    "reason": null,
    "secrets": null,
    "services": null,
    "status": "READY",
    "tags": []
}
```

### Expected behavior

Both functions should execute succesfully

### Current behavior

When function is invoked from an event the function fails.

### Impact

- [ ] Low - Annoyance, but does not impact business or functionality
- [ ] Medium - Issue can be worked around, but is causing pain
- [x] High - Blocker

### Possible solution

When a subscription invokes a function it should pass the data payload as the correct type as based on the content-type.

### Your Environment

* Dispatch CLI version (or git commit):
* Dispatch Chart version (or image[s] tag):
* Operating System and version:
* Kubernetes version (and distribution):
* Etc (any other useful environmental information):

**Comment by kars7e** [comment]
Discussion in #270 (which may seem duplicate, but this issue has more info so let's keep both).

**Comment by tenczar** [comment]
Here is an example of the python output
```
{
    "event": {
        "cloud-events-version": "0.1",
        "content-type": "application/json",
        "event-id": "0a722907-3a1f-4f24-96f4-fc75d67e2412",
        "event-time": "2018-05-16T16:03:03.168-07:00",
        "event-type": "symphony",
        "namespace": "dispatchframework.io",
        "source-id": "dispatch",
        "source-type": "dispatch"
    },
    "executedTime": -62167136217,
    "faasId": "fce63df6-048e-4540-a209-b13f1d71cf45",
    "finishedTime": -62135596800,
    "functionId": "860bc961-e968-4d78-97bc-da7f7606eab1",
    "functionName": "hello-py",
    "input": "{\"name\" : \"Jon\", \"place\" : \"Winterfell\"}",
    "logs": {
        "stderr": null,
        "stdout": null
    },
    "name": "7d634185-88a0-4977-99dd-834075362d6a",
    "reason": [
        "error running function: hello-py: cannot JSON-parse result from OpenFaaS: invalid character 'I' looking for beginning of value Internal Server Error\r\n\r\nThe server encountered an unexpected internal server error\r\n\r\n(generated by waitress)"
    ],
    "secrets": null,
    "services": null,
    "status": "ERROR",
    "tags": []
}
```

Here is the logs from the function in openfaas:
```
ERROR:waitress:Exception when serving /function/of-fce63df6-048e-4540-a209-b13f1d71cf45
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/usr/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/usr/lib/python3.6/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "main.py", line 50, in exec_function
    res.body = json.dumps({'context': {'error': err, 'logs': {'stdout': read_logs(stdout), 'stderr': read_logs(stderr)}}, 'payload': r}, ensure_ascii=False)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'AttributeError' is not JSON serializable
```
